apiVersion: v1
kind: Pod
metadata:
  name: beta-server
  namespace: team-beta
  labels:
    app: server
    team: beta
spec:
  containers:
  - name: server
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=hello-from-beta-server"
    - "-listen=:5678"
    ports:
    - containerPort: 5678