apiVersion: v1
kind: Pod
metadata:
  name: alpha-server
  namespace: team-alpha
  labels:
    app: server
    team: alpha
spec:
  containers:
  - name: server
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=hello-from-alpha-server"
    - "-listen=:5678"
    ports:
    - containerPort: 5678